"""Writes internal/markdown/emoji_table.go from Unicode's emoji-data.txt.

Run with `make emoji-table`. The table holds the Extended_Pictographic
code points, which the markdown pass removes along with the emoji
components in emoji.go.
"""

import sys
import urllib.request

UNICODE_VERSION = "17.0.0"
URL = f"https://www.unicode.org/Public/{UNICODE_VERSION}/ucd/emoji/emoji-data.txt"
OUT = "internal/markdown/emoji_table.go"


def main() -> None:
    data = urllib.request.urlopen(URL).read().decode()
    ranges = []
    for line in data.splitlines():
        line = line.split("#", 1)[0].strip()
        if not line:
            continue
        cps, prop = (part.strip() for part in line.split(";"))
        if prop != "Extended_Pictographic":
            continue
        lo, _, hi = cps.partition("..")
        ranges.append((int(lo, 16), int(hi or lo, 16)))
    ranges.sort()
    merged = []
    for lo, hi in ranges:
        if merged and lo <= merged[-1][1] + 1:
            merged[-1] = (merged[-1][0], max(hi, merged[-1][1]))
        else:
            merged.append((lo, hi))
    r16 = [r for r in merged if r[1] <= 0xFFFF]
    r32 = [r for r in merged if r[1] > 0xFFFF]
    with open(OUT, "w") as f:
        f.write("// Code generated by scripts/gen_emoji_table.py from Unicode ")
        f.write(f"{UNICODE_VERSION} emoji-data.txt. DO NOT EDIT.\n\n")
        f.write("package markdown\n\nimport \"unicode\"\n\n")
        f.write("// extendedPictographic is Unicode's Extended_Pictographic property.\n")
        f.write("var extendedPictographic = &unicode.RangeTable{\n")
        f.write("\tR16: []unicode.Range16{\n")
        for lo, hi in r16:
            f.write(f"\t\t{{0x{lo:04x}, 0x{hi:04x}, 1}},\n")
        f.write("\t},\n\tR32: []unicode.Range32{\n")
        for lo, hi in r32:
            f.write(f"\t\t{{0x{lo:x}, 0x{hi:x}, 1}},\n")
        f.write("\t},\n")
        latin = sum(1 for lo, hi in r16 if hi <= 0xFF)
        f.write(f"\tLatinOffset: {latin},\n}}\n")
    print(f"wrote {OUT}: {len(merged)} ranges", file=sys.stderr)


if __name__ == "__main__":
    main()
